### ISSUE TITLE
compiling on debian fails

### ISSUE THREAD

**Issue by kmorber** [nashcom/nsh-tools#3]
i receive the following error message on running make

Build with OpenSSL dynamically linked

gcc  -g -Wall -c -fPIC -pedantic nshmailx.cpp  -O2
In file included from /usr/include/openssl/opensslv.h:109,
                 from nshmailx.cpp:108:
/usr/include/openssl/macros.h:155:4: error: #error "OPENSSL_API_COMPAT expresses an impossible API compatibility level"
  155 | #  error "OPENSSL_API_COMPAT expresses an impossible API compatibility level"
      |    ^~~~~
make: *** [makefile:51: nshmailx.o] Fehler 1

openssl has been installed this way:

git clone https://github.com/openssl/openssl.git
cd openssl

git checkout openssl-3.2.0
./config --prefix=/usr/
make
make install

**Comment by Daniel-Nashed** [comment]
Interesting. You run into an OpenSSL incompatibility issue and open an issue in this project?
This isn't an error message thrown by nshmailx. But I took a quick look if the way I documented to compile it works.

The project allows to dynamically link using installing the OpenSSL development lib coming with the Linux version you are building with. Or statically linking with OpenSSL compiled from scratch linking with **libcrypto.a** and **libssl.a** compiled cloning the OpenSSL GitHub project.

I am not sure why you picked exactly this OpenSSL version. 
The [Tutorial: Compile and Link C/C++ applications with OpenSSL on Linux and MacOS](https://github.com/nashcom/nsh-tools/blob/main/docs/turorial_build_apps_with_openssl.md) references version 3.2.0 as an example because it was the latest version when I wrote the tutorial. If you intend to compile from scratch and statically link, you should use the latest version or at least the latest version from that code stream.

I just compiled and linked on **Debian GNU/Linux 12 (bookworm)** with **OpenSSL 3.2.3** using the steps in my tutorial.
My compile did not include the prefix and I did not install OpenSSL. I just used the compiled statically link libs from that version.

```
Nash!Com SMTP Mail Tool 1.0.5
OpenSSL 3.2.3 3 Sep 2024
(Build on: OpenSSL 3.2.3 3 Sep 2024)
```

If you want to statically link, please follow the steps I provided in the tutorial.
I can't help with your with OpenSSL errors raising from your own way installing/using it.

Just for a test I just used the latest OpenSSL version building on Debian 12.

```
Nash!Com SMTP Mail Tool 1.0.5
OpenSSL 3.5.0-dev
(Build on: OpenSSL 3.5.0-dev )
```

Without cloning OpenSSL you are compiling with the version which comes from Debian 12.
Today this would be **OpenSSL 3.0.15 3 Sep 2024** which is a good version to use.
Debian did not make the jump to a newer OpenSSL major release but keeps OpenSSL on the code stream they are on, up to date.

Statically linking is not really needed if you run it on the same machine.
I am not sure why you are installing the new OpenSSL version. 

In my tutorial I just use it to compile. Installing a new OpenSSL version might bring other challenges.
My purpose to compile OpenSSL is to use a fixed, later OpenSSL version without dependencies to be able to use it on any other machine (provided the glibc dependencies match).

Usually you don't need to statically link. The makefile of the project supports both.
Installing a new OpenSSL version on Linux is a different animal and I can't really help you with that.

I hope this helps?

**Comment by kmorber** [comment]
same problem, but i use debian 11

Build with OpenSSL statically linked

gcc  -g -Wall -c -fPIC -pedantic nshmailx.cpp -I../../openssl/include -O2
In file included from nshmailx.cpp:109:
nshmailx.cpp: In function ‘int SendSmtpMessage(const char*, const char*, const char*, const char*, const char*, const char*, const char*, const char*, const char*, const char*, const char*, const char*, const char*, const char*, bool, bool, bool, bool, bool)’:
../../openssl/include/openssl/bio.h:632:34: warning: value computed is not used [-Wunused-value]
  632 | # define BIO_flush(b)            (int)BIO_ctrl(b,BIO_CTRL_FLUSH,0,NULL)
      |                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
nshmailx.cpp:1576:9: note: in expansion of macro ‘BIO_flush’
 1576 |         BIO_flush (pBioMem);
      |         ^~~~~~~~~
../../openssl/include/openssl/bio.h:632:34: warning: value computed is not used [-Wunused-value]
  632 | # define BIO_flush(b)            (int)BIO_ctrl(b,BIO_CTRL_FLUSH,0,NULL)
      |                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
nshmailx.cpp:1701:9: note: in expansion of macro ‘BIO_flush’
 1701 |         BIO_flush (pBioMem);
      |         ^~~~~~~~~
gcc -o nshmailx nshmailx.o ../../openssl/libssl.a ../../openssl/libcrypto.a  -lresolv
/usr/bin/ld: ../../openssl/libcrypto.a(libcrypto-lib-threads_pthread.o): in function `CRYPTO_THREAD_lock_new':
threads_pthread.c:(.text+0x1e): undefined reference to `pthread_rwlock_init'
/usr/bin/ld: ../../openssl/libcrypto.a(libcrypto-lib-threads_pthread.o): in function `CRYPTO_THREAD_read_lock':
threads_pthread.c:(.text+0x55): undefined reference to `pthread_rwlock_rdlock'
/usr/bin/ld: ../../openssl/libcrypto.a(libcrypto-lib-threads_pthread.o): in function `CRYPTO_THREAD_write_lock':
threads_pthread.c:(.text+0x75): undefined reference to `pthread_rwlock_wrlock'
/usr/bin/ld: ../../openssl/libcrypto.a(libcrypto-lib-threads_pthread.o): in function `CRYPTO_THREAD_unlock':
threads_pthread.c:(.text+0x95): undefined reference to `pthread_rwlock_unlock'
/usr/bin/ld: ../../openssl/libcrypto.a(libcrypto-lib-threads_pthread.o): in function `CRYPTO_THREAD_lock_free':
threads_pthread.c:(.text+0xba): undefined reference to `pthread_rwlock_destroy'
/usr/bin/ld: ../../openssl/libcrypto.a(libcrypto-lib-threads_pthread.o): in function `CRYPTO_THREAD_run_once':
threads_pthread.c:(.text+0xe5): undefined reference to `pthread_once'
/usr/bin/ld: ../../openssl/libcrypto.a(libcrypto-lib-threads_pthread.o): in function `CRYPTO_THREAD_init_local':
threads_pthread.c:(.text+0x105): undefined reference to `pthread_key_create'
/usr/bin/ld: ../../openssl/libcrypto.a(libcrypto-lib-threads_pthread.o): in function `CRYPTO_THREAD_set_local':
threads_pthread.c:(.text+0x137): undefined reference to `pthread_setspecific'
/usr/bin/ld: ../../openssl/libcrypto.a(libcrypto-lib-threads_pthread.o): in function `CRYPTO_THREAD_cleanup_local':
threads_pthread.c:(.text+0x157): undefined reference to `pthread_key_delete'
/usr/bin/ld: ../../openssl/libcrypto.a(libcrypto-lib-threads_pthread.o): in function `CRYPTO_THREAD_get_local':
threads_pthread.c:(.text+0x123): undefined reference to `pthread_getspecific'
/usr/bin/ld: ../../openssl/libcrypto.a(libcrypto-lib-thread_posix.o): in function `ossl_crypto_thread_native_spawn':
thread_posix.c:(.text+0x4e): undefined reference to `pthread_create'
/usr/bin/ld: ../../openssl/libcrypto.a(libcrypto-lib-thread_posix.o): in function `ossl_crypto_thread_native_perform_join':
thread_posix.c:(.text+0xeb): undefined reference to `pthread_join'
/usr/bin/ld: ../../openssl/libcrypto.a(libcrypto-lib-thread_posix.o): in function `ossl_crypto_mutex_try_lock':
thread_posix.c:(.text+0x1b5): undefined reference to `pthread_mutex_trylock'
/usr/bin/ld: ../../openssl/libcrypto.a(libcrypto-lib-dso_dlfcn.o): in function `dlfcn_globallookup':
dso_dlfcn.c:(.text+0x13): undefined reference to `dlopen'
/usr/bin/ld: dso_dlfcn.c:(.text+0x26): undefined reference to `dlsym'
/usr/bin/ld: dso_dlfcn.c:(.text+0x31): undefined reference to `dlclose'
/usr/bin/ld: ../../openssl/libcrypto.a(libcrypto-lib-dso_dlfcn.o): in function `dlfcn_bind_func':
dso_dlfcn.c:(.text+0x1d7): undefined reference to `dlsym'
/usr/bin/ld: dso_dlfcn.c:(.text+0x2ce): undefined reference to `dlerror'
/usr/bin/ld: ../../openssl/libcrypto.a(libcrypto-lib-dso_dlfcn.o): in function `dlfcn_load':
dso_dlfcn.c:(.text+0x341): undefined reference to `dlopen'
/usr/bin/ld: dso_dlfcn.c:(.text+0x3c8): undefined reference to `dlclose'
/usr/bin/ld: dso_dlfcn.c:(.text+0x401): undefined reference to `dlerror'
/usr/bin/ld: ../../openssl/libcrypto.a(libcrypto-lib-dso_dlfcn.o): in function `dlfcn_pathbyaddr':
dso_dlfcn.c:(.text+0x4c2): undefined reference to `dladdr'
/usr/bin/ld: dso_dlfcn.c:(.text+0x533): undefined reference to `dlerror'
/usr/bin/ld: ../../openssl/libcrypto.a(libcrypto-lib-dso_dlfcn.o): in function `dlfcn_unload':
dso_dlfcn.c:(.text+0x6c4): undefined reference to `dlclose'
collect2: error: ld returned 1 exit status
make: *** [makefile:48: nshmailx] Fehler 1

**Comment by kmorber** [comment]
mkdir -p /local/github
cd /local/github

git clone https://github.com/openssl/openssl.git
cd openssl

git checkout openssl-3.2.3
./config
make
cd /local/github
git clone https://github.com/nashcom/nsh-tools.git
cd nsh-tools/nshmailx
make

**Comment by Daniel-Nashed** [comment]
Sorry I can't help with your OpenSSL related build issues.
It works for me in many environments and this is an open source project providing a tool.
The openssl static link libs are missing some dependencies during link.
I can't test all OS versions and combinations. This does not look like a general error and it is OpenSSL related. Not nshmailx related.

Again you are statically linking, which is probably not needed unless you want a very specific version.
I cannot spend time on something like this in my community time.

**Comment by Daniel-Nashed** [comment]
Just tried to compile & link on Debian 11.
The native way doesn't work because Debian 11 it is still on OpenSSL 1.1.1.
nshmailx requires at least OpenSSL 3.0.

Linking with OpenSSL 3.2.3 also resulted in the same errors for me.

There isn't anything I can do for you if you are staying on Debian 11. 
Compiling on Debian 12 will not help because because of glibc you can't run it on Debian 11.

**Comment by Daniel-Nashed** [comment]
Not sure you looked into all my details I provided. But there is nothing I can do in the combination of software you are running.
I think I outlined all the details and I can't provide more support as part of this community project.
